# Generated by Django 5.2.8 on 2025-12-14 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('racha_dias', models.IntegerField(default=0, verbose_name='Días Seguidos (Racha)')),
                ('dias_totales', models.IntegerField(default=0, verbose_name='Días Totales Acumulados')),
                ('puntos', models.IntegerField(default=0, verbose_name='Puntos Acumulados')),
                ('tiempo_terapia', models.IntegerField(default=0, verbose_name='Minutos de Terapia Hoy')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Paciente',
                'verbose_name_plural': 'Perfiles de Pacientes',
            },
        ),
    ]
