# Generated by Django 5.2.8 on 2025-12-14 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilpaciente',
            options={'verbose_name': 'Perfil de Usuario (Médico/Paciente)', 'verbose_name_plural': 'Perfiles de Usuarios'},
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='es_medico',
            field=models.BooleanField(default=False, verbose_name='¿Es Médico?'),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='medico_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_supervisados', to=settings.AUTH_USER_MODEL, verbose_name='Médico Supervisor (Opcional)'),
        ),
    ]
