# Generated by Django 5.2.8 on 2025-12-17 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_perfilpaciente_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilpaciente',
            options={},
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='altura',
            field=models.IntegerField(blank=True, null=True, verbose_name='Altura (cm)'),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='edad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='lado_afectado',
            field=models.CharField(blank=True, choices=[('Izquierdo', 'Lado Izquierdo'), ('Derecho', 'Lado Derecho'), ('Ambos', 'Ambos Lados'), ('Ninguno', 'Sin afectación motora')], max_length=20, null=True, verbose_name='Lado Afectado (Hemiplejia)'),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='peso',
            field=models.IntegerField(blank=True, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='perfilpaciente',
            name='dias_totales',
            field=models.IntegerField(default=0, verbose_name='Días Totales'),
        ),
        migrations.AlterField(
            model_name='perfilpaciente',
            name='medico_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_supervisados', to=settings.AUTH_USER_MODEL, verbose_name='Médico Supervisor'),
        ),
        migrations.AlterField(
            model_name='perfilpaciente',
            name='puntos',
            field=models.IntegerField(default=0, verbose_name='Puntos'),
        ),
        migrations.AlterField(
            model_name='perfilpaciente',
            name='racha_dias',
            field=models.IntegerField(default=0, verbose_name='Días Seguidos'),
        ),
        migrations.AlterField(
            model_name='perfilpaciente',
            name='tiempo_terapia',
            field=models.IntegerField(default=0, verbose_name='Minutos Hoy'),
        ),
    ]
