# Generated by Django 5.2.8 on 2025-12-17 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_perfilpaciente_options_perfilpaciente_altura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionDeJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('puntos', models.IntegerField(default=0, verbose_name='Puntos ganados')),
                ('tiempo_jugado', models.IntegerField(default=0, verbose_name='Segundos jugados')),
                ('juego', models.CharField(default='Memory', max_length=50, verbose_name='Nombre del Juego')),
                ('nivel_alcanzado', models.IntegerField(default=1, verbose_name='Nivel')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='core.perfilpaciente')),
            ],
            options={
                'verbose_name': 'Sesión de Juego',
                'verbose_name_plural': 'Historial de Sesiones',
                'ordering': ['-fecha'],
            },
        ),
    ]
