# Generated by Django 5.2.8 on 2026-01-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sesiondejuego'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpaciente',
            name='fecha_ultima_evaluacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha última evaluación'),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='nivel_asignado',
            field=models.IntegerField(default=1, verbose_name='Nivel de Dificultad (1-5)'),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='puntuacion_cognitiva',
            field=models.IntegerField(default=0, verbose_name='Score Cognitivo (0-30)'),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='puntuacion_motora',
            field=models.IntegerField(default=0, verbose_name='Score Motor (0-100)'),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='test_completado',
            field=models.BooleanField(default=False, verbose_name='¿Evaluación Inicial Completada?'),
        ),
    ]
