# Generated by Django 5.2.8 on 2026-02-09 15:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_perfilpaciente_fecha_ultima_evaluacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesiondejuego',
            options={'ordering': ['-fecha']},
        ),
        migrations.RemoveField(
            model_name='perfilpaciente',
            name='puntos',
        ),
        migrations.RemoveField(
            model_name='perfilpaciente',
            name='puntuacion_cognitiva',
        ),
        migrations.RemoveField(
            model_name='perfilpaciente',
            name='tiempo_terapia',
        ),
        migrations.RemoveField(
            model_name='sesiondejuego',
            name='nivel_alcanzado',
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='puntos_totales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='puntuacion_total_moca',
            field=models.IntegerField(default=0, verbose_name='MoCA Total (0-30)'),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='score_abstraccion',
            field=models.IntegerField(default=0, verbose_name='Abstracción'),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='score_atencion',
            field=models.IntegerField(default=0, verbose_name='Atención'),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='score_identificacion',
            field=models.IntegerField(default=0, verbose_name='Identificación'),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='score_lenguaje',
            field=models.IntegerField(default=0, verbose_name='Lenguaje'),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='score_orientacion',
            field=models.IntegerField(default=0, verbose_name='Orientación'),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='score_recuerdo',
            field=models.IntegerField(default=0, verbose_name='Recuerdo Diferido'),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='score_visuoespacial',
            field=models.IntegerField(default=0, verbose_name='Visuoespacial/Ejecutiva'),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='tiempo_terapia_hoy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sesiondejuego',
            name='completado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sesiondejuego',
            name='detalles',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles JSON'),
        ),
        migrations.AddField(
            model_name='sesiondejuego',
            name='nivel_jugado',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='perfilpaciente',
            name='altura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilpaciente',
            name='dias_totales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfilpaciente',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilpaciente',
            name='fecha_ultima_evaluacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilpaciente',
            name='lado_afectado',
            field=models.CharField(blank=True, choices=[('Izquierdo', 'Lado Izquierdo'), ('Derecho', 'Lado Derecho'), ('Ambos', 'Ambos Lados'), ('Ninguno', 'Sin afectación motora')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfilpaciente',
            name='medico_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_supervisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfilpaciente',
            name='nivel_asignado',
            field=models.IntegerField(default=1, verbose_name='Nivel (1-5)'),
        ),
        migrations.AlterField(
            model_name='perfilpaciente',
            name='peso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilpaciente',
            name='racha_dias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfilpaciente',
            name='test_completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sesiondejuego',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha UTC'),
        ),
        migrations.AlterField(
            model_name='sesiondejuego',
            name='juego',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='sesiondejuego',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sesiondejuego',
            name='tiempo_jugado',
            field=models.IntegerField(default=0, verbose_name='Segundos'),
        ),
    ]
