# Generated by Django 5.2.8 on 2026-02-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sesiondejuego_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpaciente',
            name='nivel_cognitivo',
            field=models.IntegerField(default=1, verbose_name='Nivel Cognitivo (1-5)'),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='nivel_lenguaje',
            field=models.IntegerField(default=1, verbose_name='Nivel Lenguaje (1-5)'),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='nivel_motor',
            field=models.IntegerField(default=1, verbose_name='Nivel Motor (1-5)'),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='puntuacion_cognitiva',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfilpaciente',
            name='nivel_asignado',
            field=models.IntegerField(default=1, verbose_name='Nivel Global (Legacy)'),
        ),
    ]
