# Generated by Django 5.2.8 on 2026-02-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_perfilpaciente_nivel_cognitivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesiondejuego',
            name='dificultad_percibida',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesiondejuego',
            name='estado_animo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
