# Generated by Django 5.2.8 on 2026-03-15 21:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notaespecialista'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpaciente',
            name='ciudad_residencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad de Residencia'),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='lugar_habitual',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar Habitual (Ej. Casa, Hospital)'),
        ),
        migrations.CreateModel(
            name='EvaluacionMoCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de realización')),
                ('score_visuoespacial', models.IntegerField(default=0)),
                ('score_identificacion', models.IntegerField(default=0)),
                ('score_atencion', models.IntegerField(default=0)),
                ('score_lenguaje', models.IntegerField(default=0)),
                ('score_abstraccion', models.IntegerField(default=0)),
                ('score_recuerdo', models.IntegerField(default=0)),
                ('score_orientacion', models.IntegerField(default=0)),
                ('score_total', models.IntegerField(default=0, verbose_name='Nota Final (0-30)')),
                ('dibujo_cubo_b64', models.TextField(blank=True, null=True)),
                ('dibujo_reloj_b64', models.TextField(blank=True, null=True)),
                ('audio_frase1_b64', models.TextField(blank=True, null=True)),
                ('audio_frase2_b64', models.TextField(blank=True, null=True)),
                ('audio_fluidez_b64', models.TextField(blank=True, null=True)),
                ('audio_tren_b64', models.TextField(blank=True, null=True)),
                ('audio_reloj_b64', models.TextField(blank=True, null=True)),
                ('audio_recuerdo_b64', models.TextField(blank=True, null=True)),
                ('transcripcion_frase1', models.TextField(blank=True, null=True)),
                ('transcripcion_frase2', models.TextField(blank=True, null=True)),
                ('transcripcion_fluidez', models.TextField(blank=True, null=True)),
                ('abstraccion_tren_respuesta', models.TextField(blank=True, null=True)),
                ('abstraccion_reloj_respuesta', models.TextField(blank=True, null=True)),
                ('transcripcion_recuerdo', models.TextField(blank=True, null=True)),
                ('datos_completos_raw', models.JSONField(blank=True, null=True, verbose_name='JSON Íntegro del Frontend')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_moca', to='core.perfilpaciente')),
            ],
            options={
                'ordering': ['-fecha_evaluacion'],
            },
        ),
    ]
