# Generated by Django 5.2.8 on 2026-05-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_evaluacionmoca_abstraccion_reloj_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpaciente',
            name='hemiparesia_dominante',
            field=models.CharField(blank=True, choices=[('Si', 'Sí'), ('No', 'No')], max_length=2, null=True, verbose_name='Hemiparesia dominante'),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='hemisferio_afectado',
            field=models.CharField(blank=True, choices=[('Izquierdo', 'Izquierdo'), ('Derecho', 'Derecho'), ('Bilateral', 'Bilateral'), ('Ninguno', 'Ninguno')], max_length=15, null=True, verbose_name='Hemisferio afectado'),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='meses_desde_ictus',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Meses desde el ictus'),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='tipo_ictus',
            field=models.CharField(blank=True, choices=[('Isquemico', 'Isquémico'), ('Hemorragico', 'Hemorrágico')], max_length=15, null=True, verbose_name='Tipo de ictus'),
        ),
    ]
