# Generated by Django 5.2.8 on 2026-05-19 11:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_perfilpaciente_hemiparesia_dominante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesiondejuego',
            name='degradacion_porcentaje',
            field=models.FloatField(blank=True, null=True, verbose_name='Degradación vs TR Ideal (%)'),
        ),
        migrations.AddField(
            model_name='sesiondejuego',
            name='errores_cometidos',
            field=models.IntegerField(default=0, verbose_name='Errores en la partida'),
        ),
        migrations.AddField(
            model_name='sesiondejuego',
            name='tiempo_reaccion_ms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo de Reacción (ms)'),
        ),
        migrations.CreateModel(
            name='SesionTerapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima_actividad', models.DateTimeField(default=django.utils.timezone.now)),
                ('vas_inicial', models.IntegerField(blank=True, null=True, verbose_name='Cansancio inicial (1-10)')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_terapia', to='core.perfilpaciente')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='sesiondejuego',
            name='sesion_terapia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas', to='core.sesionterapia'),
        ),
        migrations.CreateModel(
            name='MarcaPersonalTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juego', models.CharField(max_length=100)),
                ('nivel', models.IntegerField()),
                ('TR_ideal', models.IntegerField(blank=True, null=True, verbose_name='TR Ideal (ms)')),
                ('partidas_base_calculadas', models.IntegerField(default=0)),
                ('tiempo1', models.IntegerField(blank=True, null=True)),
                ('tiempo2', models.IntegerField(blank=True, null=True)),
                ('tiempo3', models.IntegerField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas_tr', to='core.perfilpaciente')),
            ],
            options={
                'unique_together': {('paciente', 'juego', 'nivel')},
            },
        ),
    ]
