# Generated by Django 5.2.8 on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_sesiondejuego_degradacion_porcentaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesiondejuego',
            name='fc_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='FC Mínima (bpm)'),
        ),
        migrations.AddField(
            model_name='sesiondejuego',
            name='fc_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='FC Máxima (bpm)'),
        ),
        migrations.AddField(
            model_name='sesiondejuego',
            name='fc_avg',
            field=models.IntegerField(blank=True, null=True, verbose_name='FC Media (bpm)'),
        ),
        migrations.AddField(
            model_name='sesiondejuego',
            name='fc_serie',
            field=models.JSONField(blank=True, null=True, verbose_name='Serie FC segundo a segundo (bpm)'),
        ),
    ]
